import "./globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className} bg-cyan-bg`}>
        <div className="bg-header-mobile h-[156px] w-full bg-no-repeat bg-cover md:bg-header-desktop bg-dark-cyan absolute" />
        <main className="relative z-10 max-w-[1158px] mx-auto px-[24px]">
          {children}
        </main>
      </body>
    </html>
  );
}
